services:
  web:
    image: priyanshu842/indeedlms:latest
    container_name: indeedlms
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn LMS.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - proxy-network

volumes:
  static_volume:
  media_volume:

networks:
  proxy-network:
    external: true